# Site
repository: Bart0wski/Bart0wski.github.io
favicon: images/5g.ico
darkmode: false

# Allow users to enable/disable darkmode on their end (using cookies)
darktoggle: true

# Personal info

name: François Beugin
title: Wireless Network Engineer
email: beugin.francois@gmail.com
address: Boulogne-Billancourt • France
website: www.fbeugin.fr

# Social links
#twitter_username: facespics
github_username:  Bart0wski
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: francoisbeugin
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
resume: CV_FBEUGIN_english.pdf

# Google Analytics and Tag Manager
#gtag: UA-155264465-1

# About Section
# about_title: Profile
about_profile_image: images/hanok.jpg
about_content: |
  Hello, I'm François BEUGIN and I'm an Expert Wireless Network Engineer working on 4G and 5G Technologies at SFR.
  Before that, I was working as a Wireless Network Engineer at Huawei France.
  I'm also interested in IoT and analyzing data as I can do during my work.
  I had the opportunity to work on 5G SA and VoNR.

  I am most skilled in: <mark>Python</mark>, <mark>Mobile Networks</mark> and <mark>Data Analysis</mark>
# Skills Section
# skills_title: Skills

# Projects Section
projects_title: Projects at IMT Atlantique

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certifications Section
# certifications_title: Certifications

# More Section
more_title: Hobbies
more_content: |
  Alongside my interests in programming and mobile networks some of my other interests and hobbies are:
   - 🕹️ Gaming
   - 🏓 Table Tennis
   - 🎴 Bridge

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme
