# Site
repository: Bart0wski/Bart0wski.github.io
favicon: images/5g.ico
darkmode: false

# Allow users to enable/disable darkmode on their end (using cookies)
darktoggle: true

# Personal info

name: François Beugin
title: Wireless Network Engineer
email: beugin.francois@gmail.com
address: Boulogne-Billancourt • France
website: fbeugin.fr

# Social links
#twitter_username: facespics
github_username:  Bart0wski
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: francoisbeugin
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# Google Analytics and Tag Manager
#gtag: UA-155264465-1

# About Section
# about_title: Profile
about_profile_image: images/kakao.jpg
about_content: |
  Hi, welcome to my personal web page, I'm François and I'm a freshly graduate student from IMT Atlantique, I'm currently doing my final internship as a Radio System Engineer in Bouygues Telecom (French Mobile ISP). I'm also interested in IoT and analyzing data.

  I am most skilled in: <mark>Python</mark> and <mark>mobile networks</mark>
# Skills Section
# skills_title: Skills

# Projects Section
projects_title: Most starred open-source projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certifications Section
# certifications_title: Certifications

# More Section
more_title: Hobbies
more_content: |
  Alongside my interests in software development some of my other interests and hobbies are:
   - 🕹️ Gaming
   - 🏓 Table Tennis
   - 🃏 Bridge

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme
