# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: François Beugin
title: Junior Network Enginner
email: beugin.francois@gmail.com
website: bart0wski.github.io

# Social links
#twitter_username: facespics
github_username:  Bart0wski
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: francois.beugin
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/kakao.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, welcome to my personal web page, I'm François and I'm a freshly graduate student from IMT Atlantique, I'm currently doing my final internship as a Radio System Engineer in Bouygues Telecom (French Mobile ISP). I'm also interested in IoT and analyzing data.

  I am most skilled in: <mark>Python</mark> and <mark>mobile networks</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Bridge
   - Gaming
   - Table Tennis
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg) ===>How to make hyperlink

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
